### ISSUE TITLE
More complex HTTP waiting operations

### ISSUE THREAD

**Issue by dnnrly** [dnnrly/wait-for#9]
**Is your feature request related to a problem? Please describe.**
At the moment, the only option for HTTP operations is GET returning a 2XX result. It would be good if we could use different methods. Perhaps a POST with a method body or something.

I guess some questions are:
1. How would it be configured?
2. Would it be valid to specify as a CLI argument based target?

**Comment by Safouene1** [comment]
I've been thinking about the POST request and how to implement a wait-for for it.
I propose that we consider the POST request successful if if returns http status **400** error code only. 

The main purpose of the wait for post request is to check if the endpoint is working and when we don't pass any data at all or correct data the POST request returns 400 status code .

> A 400 means that the request was malformed. In other words, the data stream sent by the client to the server didn't follow the rules. 

Since we do not care whether the request have the correct data or not I think using 400 status code is a good solution.
@dnnrly  What do you think?

**Comment by dnnrly** [comment]
Yes, I tend to agree. How about making the expected response code configurable? Regex maybe, or is that too complex?

**Comment by Safouene1** [comment]
I've implemented Regex output in HTTP calls for example 
`wait-for -regex=400 https://github.com/dnnrly/wait-for/issues/9 `
outputs 
` 200 status Code and 400 regex didn't match in https://github.com/dnnrly/wait-for/issues/9
`
It works fine and doesn't interrupt the operation if the regex pattern match ,I will send a pull request as soon as I finish with writing test
Examples : 

```
./wait-for   -regex=[0-9]{3} https://https://github.com
 started waiting for https://https://github.com
 finished waiting for https://github.com
```

```
./wait-for   -regex=[4-9]{1} https://https://github.com
 started waiting for https://github.com
error while waiting for https://github.com: 200 status Code and [4-9]{1} regex didn't match in https://github.com
error while waiting for https://github.com: 200 status Code and [4-9]{1} regex didn't match in https://github.com
error while waiting for https://github.com: 200 status Code and [4-9]{1} regex didn't match in https://github.com
timed out waiting for https://github.com: 200 status Code and [4-9]{1} regex didn't match in https://github.com
```
